# Generated by Django 4.0.4 on 2022-05-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=999, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='bruto',
            field=models.FloatField(max_length=999),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=999),
        ),
        migrations.AlterField(
            model_name='job',
            name='neto',
            field=models.FloatField(max_length=999),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=999),
        ),
    ]
