# Generated by Django 4.0.4 on 2022-05-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_company_name_alter_job_bruto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIAccessKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=999)),
                ('name', models.CharField(max_length=999)),
            ],
        ),
    ]
