# Generated by Django 4.0.4 on 2022-05-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_job_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('numofjobs', models.IntegerField()),
                ('numofcompanies', models.IntegerField()),
                ('numofactivejobs', models.IntegerField()),
                ('average_neto', models.FloatField()),
                ('average_bruto', models.FloatField()),
                ('delta_neto', models.FloatField()),
                ('delta_bruto', models.FloatField()),
            ],
        ),
    ]
